# Generated by Django 4.1.2 on 2022-10-16 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('value', models.DecimalField(decimal_places=6, max_digits=7)),
                ('cpf', models.CharField(max_length=11)),
                ('card_number', models.CharField(max_length=12)),
                ('time', models.TimeField()),
                ('owner', models.CharField(max_length=14)),
                ('store', models.CharField(max_length=19)),
            ],
        ),
    ]
