# Generated by Django 4.1.1 on 2022-10-18 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transaction_types', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cpf', models.CharField(max_length=11)),
                ('card_number', models.CharField(max_length=12)),
                ('time', models.TimeField()),
                ('owner', models.CharField(max_length=14)),
                ('store', models.CharField(max_length=19)),
                ('tr_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transaction_types.transactiontype')),
            ],
        ),
    ]
