# Generated by Django 4.1.2 on 2022-10-16 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=24)),
                ('nature', models.CharField(max_length=8)),
                ('sign', models.CharField(choices=[('+', 'Plus'), ('-', 'Minus')], default='+', max_length=1)),
            ],
        ),
    ]
