# Generated by Django 4.1.2 on 2022-10-16 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_types', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiontype',
            name='description',
            field=models.CharField(max_length=24, unique=True),
        ),
    ]
